# Generated by Django 4.1.13 on 2023-12-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('domain', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=2053)),
            ],
        ),
    ]
